--CREATE USER
CREATE TABLE USERS (
	USER_ID			VARCHAR2(20)		NOT NULL,
	PASSWORD		VARCHAR2(20)		NOT NULL,
	USER_NAME		VARCHAR2(20)		NOT NULL,
	USER_NAME_KANA	VARCHAR2(20)		NOT NULL,
	NICKNAME		VARCHAR2(30)		NOT NULL,
	JOIN_DATE		DATE,
	LAST_LOGIN_DATE	DATE,
	POSITION		VARCHAR2(10),
	RANK_ID			INTEGER				NOT NULL,
	ADDRESS			VARCHAR2(100)		NOT NULL,
	EMAIL			VARCHAR2(100)		NOT NULL,
	
	CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
);


