--CREATE USER
CREATE TABLE USERS (
   USER_ID         VARCHAR2(20)      NOT NULL,
   PASSWORD      VARCHAR2(20)      NOT NULL,
   USER_NAME      VARCHAR2(20)      NOT NULL,
   USER_NAME_KANA   VARCHAR2(20)      NOT NULL,
   NICKNAME      VARCHAR2(30)      NOT NULL,
   JOIN_DATE      DATE,
   LAST_LOGIN_DATE   DATE,
   POSITION      VARCHAR2(10),
   RANK_ID         INTEGER            NOT NULL,
   ADDRESS         VARCHAR2(100)      NOT NULL,
   EMAIL         VARCHAR2(100)      NOT NULL,
   
   CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_RANK (
	RANK_ID      INTEGER        NOT NULL,
	RANK_NAME    VARCHAR2(20)   NOT NULL,
	
	
   CONSTRAINT RANK_ID_PK PRIMARY KEY (RANK_ID)
);

CREATE TABLE USER_PASS_CHG (
	USER_ID         VARCHAR2(20)      NOT NULL,
	PASS_CHG_DATE   DATE,
	PASS_CHG_FLG    CHAR              NOT NULL,
	
	CONSTRAINT USER_PASS_CHG_USER_ID_PK PRIMARY KEY (USER_ID)
);
commit;
SELECT * FROM USERS; 
SELECT * FROM USER_RANK; 
SELECT * FROM USER_PASS_CHG; 

INSERT INTO USERS VALUES('jwnam0661', 'rkswl0671', 'NAM JONGWON', '«Ê«à', '«Ç«Ö'
, sysdate, sysdate, 'test', 300, 'testAdd', 'jwnam0661@naver.com');
INSERT INTO USERS VALUES('dbstngus91', 'apfhd2004', 'YOON SUHYUN', '«æ«ó«¹«Ò«ç«ó', '¾¥'
, sysdate, sysdate, 'test', 100, 'testAdd', 'dbstngus91@gmail.com');
INSERT INTO USERS VALUES('test', 'test', 'test', 'test', '«Ç«Ö'
, sysdate, sysdate, 'test', 600, 'testAdd', 'test@test.com');
INSERT INTO USERS VALUES('test2', 'test2', 'test2', 'test2', '«Ç«Ö'
, sysdate, sysdate, 'test', 700, 'testAdd', 'test@test.com');
UPDATE USERS SET RANK_ID=300 WHERE USER_ID = 'jwnam0661';
UPDATE USERS SET RANK_ID=300 WHERE USER_ID = 'jwnam0661';

INSERT INTO USER_RANK VALUES(100, 'Admin'); 
INSERT INTO USER_RANK VALUES(200, 'Silver');
INSERT INTO USER_RANK VALUES(300, 'Gold');
INSERT INTO USER_RANK VALUES(400, 'Diamond');
INSERT INTO USER_RANK VALUES(500, 'Platinum');
INSERT INTO USER_RANK VALUES(600, 'Test');

INSERT INTO USER_PASS_CHG VALUES('jwnam0661', SYSDATE, '0'); 
INSERT INTO USER_PASS_CHG VALUES('dbstngus91', SYSDATE, '0'); 
INSERT INTO USER_PASS_CHG VALUES('test', SYSDATE, '0');
