SELECT * FROM USERS;
SELECT * FROM USER_RANK;
SELECT * FROM USER_PASS_CHG;

SELECT A.USER_ID, A.RANK_ID, B.RANK_NAME
FROM
	USERS A
	INNER JOIN USER_RANK B ON A.RANK_ID = B.RANK_ID
WHERE
	B.RANK_ID = 100
	AND A.USER_ID = 'dbstngus91';



select D.PASS_CHG_DATE, C.USER_ID, C.RANK_NAME
FROM
	(
		SELECT
			A.USER_ID, B.RANK_NAME
		FROM
			USERS A
			INNER JOIN USER_RANK B ON A.RANK_ID = B.RANK_ID
		WHERE
			A.USER_ID = 'jwnam0661'
	) C
	INNER JOIN USER_PASS_CHG D ON C.USER_ID = D.USER_ID
-- WHERE
-- 	D.USER_ID = 'jwnam0661';


--종원이가 마지막 비번변경 날짜와 회원등급  취득
SELECT
	A.USER_ID, B.RANK_NAME, D.PASS_CHG_DATE
FROM
	USERS A
	INNER JOIN USER_RANK B ON A.RANK_ID = B.RANK_ID
	INNER JOIN USER_PASS_CHG D ON A .USER_ID = D.USER_ID
WHERE
	A.USER_ID = 'jwnam0661';

--모든 유저의 마지막 비번변경 날짜와 회원등급  취득
SELECT
	A.USER_ID, B.RANK_NAME, D.PASS_CHG_DATE
FROM
	USERS A
	LEFT JOIN USER_RANK B ON A.RANK_ID = B.RANK_ID
	LEFT JOIN USER_PASS_CHG D ON A .USER_ID = D.USER_ID
;

select D.PASS_CHG_DATE, C.USER_ID, C.RANK_NAME
FROM
	(
		SELECT
			A.USER_ID, B.RANK_NAME
		FROM
			USERS A
			LEFT OUTER JOIN USER_RANK B ON A.RANK_ID = B.RANK_ID
	) C
	LEFT JOIN USER_PASS_CHG D ON C.USER_ID = D.USER_ID
;

SELECT * FROM USERS;


WITH USR_R AS(
	SELECT * FROM USER_RANK
)
SELECT * FROM
USERS A
INNER JOIN USR_R tmp ON A.RANK_ID = tmp.RANK_ID
;